import type { Metadata } from "next";
import { Nunito_Sans, Noto_Sans_Arabic } from "next/font/google";
import "./globals.css";
import UiProvider from "@/services/context/UiProvider";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import "@ant-design/v5-patch-for-react-19";

const nunitoSans = Nunito_Sans({
   variable: "--font-nunito-sans",
   subsets: ["latin"],
});
export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};
const notoSans = Noto_Sans_Arabic({
   variable: "--font-noto-sans",
   subsets: ["arabic"],
});

export default async function RootLayout({
   children,
   params,
}: {
   children: React.ReactNode;
   params: Promise<{ locale: string }>;
}) {
   const { locale } = await params;

   if (!hasLocale(routing.locales, locale)) {
      notFound();
   }
   return (
      <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
         <head>
            <script
               dangerouslySetInnerHTML={{
                  __html: `
               (function() {
                const lightTheme = {
                  primary: "#4880FF",
                  foreground: "#ffffff",
                  "background-dark": "#F5F6FA",
                  border: "#D5D5D5",
                  text: "#202224",
                  "text-inverse": "#FFFFFF",
                  "text-light": "#fff",
                  background: "#F5F6FA",
                  warning: "#FEC53D",
                  danger: "#F93C65",
                  "danger-light": "#FF9066",
                  success: "#00B69B",
                  purple: "#8280FF",
                  "purple-opacity": "#8280FF33",
                  "warning-opacity": "#FEC53D33",
                  "danger-opacity": "#F93C6533",
                  "success-opacity": "#00B69B33",
                  delivered: "#00B69B",
                  pending: "#FCBE2D",
                  rejected: "#FD5454",
                  "bg-table-header": "#F1F4F9"
                };
                
                const root = document.documentElement;
                Object.entries(lightTheme).forEach(([key, value]) => {
                  root.style.setProperty('--c-' + key, value);
                });
                
                // Add smooth transitions for theme changes
                root.style.setProperty('transition', 'background-color 0.2s ease, color 0.2s ease');
              })();
            `,
               }}
            />
         </head>
         <body
            className={`${nunitoSans.variable} antialiased ${notoSans.variable}`}>
            <NextIntlClientProvider>
               <UiProvider locale={locale}>{children}</UiProvider>
            </NextIntlClientProvider>
         </body>
      </html>
   );
}
