import type { Metadata } from "next";
import {
   Geist,
   Geist_Mono,
   Nunito_Sans,
   Noto_Sans_Arabic,
} from "next/font/google";
import "./globals.css";
import UiProvider from "@/services/context/UiProvider";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import "@ant-design/v5-patch-for-react-19";
import { ConfigProvider } from "antd";

import arEG from "antd/locale/ar_EG";
import enUS from "antd/locale/en_US";

const nunitoSans = Nunito_Sans({
   variable: "--font-nunito-sans",
   subsets: ["latin"],
});
export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};
const notoSans = Noto_Sans_Arabic({
   variable: "--font-noto-sans",
   subsets: ["arabic"],
});

export default async function RootLayout({
   children,
   params,
}: {
   children: React.ReactNode;
   params: Promise<{ locale: string }>;
}) {
   // Ensure that the incoming `locale` is valid
   const { locale } = await params;
   if (!hasLocale(routing.locales, locale)) {
      notFound();
   }
   console.log(locale);
   return (
      <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
         <body
            className={`${nunitoSans.variable} antialiased ${notoSans.variable} `}>
            <UiProvider>
               <ConfigProvider locale={locale === "ar" ? arEG : enUS}>
                  <NextIntlClientProvider>{children}</NextIntlClientProvider>
               </ConfigProvider>
            </UiProvider>
         </body>
      </html>
   );
}
